config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :storefronts
  resources :products
  devise_for :users, controllers: { registrations: "registrations" }

  root 'welcome#index'
  post 'add_to_cart' => 'cart#add_to_cart'
  get 'view_cart' => 'cart#view_cart'
  

end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  authorize_resource
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new(user_id: current_user.id)
    @profile.save

    redirect_to edit_profile_path(@profile)
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :user_id)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<section>
  <div class="container">
    <div class="columns">
      <div class="column is-offset-3">
        <h2 class="title is-2">Edit Profile</h2>
        <hr>
        <%= form_for(@profile) do |f| %>
          <% if @profile.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

              <ul>
              <% @profile.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <label class="label">Name</label>
          <p class="control">
            <%= f.text_field :name, class: 'input', placeholder: @profile.name %>
          </p>
          <div class="field">
            <%= f.hidden_field :user_id, value: current_user.id %>
          </div>
          <div class="actions">
            <%= f.submit 'Update Profile', class: 'button is-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/profiles/_header.html.erb
<section class="hero is-primary is-medium" id="banner-slide">
  <div class="hero-body">
	  <div class="container">
		  <div class="columns">
		  	<div class="column is-offset-3">
			  	<h1 class="title is-1">
			  			<%= @profile.name %>
			  			<% if can? :manage, Profile, :user_id => current_user.id %>
		        		<%= link_to 'Edit Profile', edit_profile_path(@profile), class: "button is-white is-outlined is-pulled-right" %>
		        	<% end %>
		      </h1>
	      </div>
      </div>
	  </div>
	</div>
</section>

<div class="container" id="circle-container">
	<div id="circle">
	</div>
</div>

app/views/profiles/edit.html.erb
<%= render 'header' %>

<%= render 'form' %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.name %></td>
        <td><%= profile.user_id %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<%= render 'header' %>