config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :storefronts
  resources :products
  devise_for :users, controllers: { registrations: "registrations" }

  root 'welcome#index'
  post 'add_to_cart' => 'cart#add_to_cart'
  get 'view_cart' => 'cart#view_cart'
  

end

app/models/storefront.rb
class Storefront < ActiveRecord::Base
	belongs_to :user
	has_many :products
end

app/controllers/storefronts_controller.rb
class StorefrontsController < ApplicationController
  authorize_resource
  before_action :set_storefront, only: [:show, :edit, :update, :destroy]

  # GET /storefronts
  # GET /storefronts.json
  def index
    @storefronts = Storefront.all
  end

  # GET /storefronts/1
  # GET /storefronts/1.json
  def show
  end

  # GET /storefronts/new
  def new
    @storefront = Storefront.new
  end

  # GET /storefronts/1/edit
  def edit
  end

  # POST /storefronts
  # POST /storefronts.json
  def create
    @storefront = Storefront.new(storefront_params)

    respond_to do |format|
      if @storefront.save
        format.html { redirect_to @storefront, notice: 'Storefront was successfully created.' }
        format.json { render :show, status: :created, location: @storefront }
      else
        format.html { render :new }
        format.json { render json: @storefront.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /storefronts/1
  # PATCH/PUT /storefronts/1.json
  def update
    respond_to do |format|
      if @storefront.update(storefront_params)
        format.html { redirect_to @storefront, notice: 'Storefront was successfully updated.' }
        format.json { render :show, status: :ok, location: @storefront }
      else
        format.html { render :edit }
        format.json { render json: @storefront.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /storefronts/1
  # DELETE /storefronts/1.json
  def destroy
    @storefront.destroy
    respond_to do |format|
      format.html { redirect_to storefronts_url, notice: 'Storefront was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_storefront
      @storefront = Storefront.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def storefront_params
      params.require(:storefront).permit(:name, :info, :user_id)
    end
end

app/helpers/storefronts_helper.rb
module StorefrontsHelper
end

app/views/storefronts/_form.html.erb
<section>
  <div class="container">
    <div class="columns">
      <div class="column is-offset-3">
        <h2 class="title is-2">Edit Storefront</h2>
        <hr>
        <%= form_for(@storefront) do |f| %>
          <% if @storefront.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@storefront.errors.count, "error") %> prohibited this storefront from being saved:</h2>

              <ul>
              <% @storefront.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <label class="label">Name</label>
          <p class="control">
            <%= f.text_field :name, class: 'input', placeholder: @storefront.name %>
          </p>
          <label class="label">Info</label>
          <p class="control">
            <%= f.text_area :info, class: 'textarea', placeholder: @storefront.info %>
          </p>
          <div class="field">
            <%= f.hidden_field :user_id, value: current_user.id %>
          </div>
          <div class="actions">
            <%= f.submit 'Update Storefront', class: 'button is-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/storefronts/_header.html.erb
<section class="hero is-primary is-medium" id="banner-slide">
  <div class="hero-body">
	  <div class="container">
		  <div class="columns">
		  	<div class="column is-offset-3">
			  	<h1 class="title is-1">
		        <%= @storefront.name %>
		        <% if can? :manage, Storefront, :user_id => current_user.id %>
	        		<%= link_to 'Edit Storefront', edit_storefront_path(@storefront), class: "button is-white is-outlined pull-right" %>
	        	<% end %>  
		      </h1>
	      </div>
      </div>
	  </div>
	</div>
</section>

<div class="container" id="circle-container">
	<div id="circle">
	</div>
</div>

app/views/storefronts/_storefront.html.erb
<div class="column is-12">
	<div class="box">
	  <article class="media">
	    <div class="media-left">
	      <figure class="image is-64x64">
	        <img src="http://placehold.it/128x128" alt="Image">
	      </figure>
	    </div>
	    <div class="media-content">
	      <div class="content">
	        <p>
	          <strong><%= link_to storefront.name, storefront %></strong>
	          <br>
	          <%= storefront.info %>
	        </p>
	      </div>
	    </div>
	  </article>
	</div>
</div>

app/views/storefronts/edit.html.erb
<%= render 'header' %>

<%= render 'form' %>

app/views/storefronts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Storefronts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Info</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @storefronts.each do |storefront| %>
      <tr>
        <td><%= storefront.name %></td>
        <td><%= storefront.info %></td>
        <td><%= storefront.user_id %></td>
        <td><%= link_to 'Show', storefront %></td>
        <td><%= link_to 'Edit', edit_storefront_path(storefront) %></td>
        <td><%= link_to 'Destroy', storefront, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Storefront', new_storefront_path %>

app/views/storefronts/new.html.erb
<h1>New Storefront</h1>

<%= render 'form' %>

<%= link_to 'Back', storefronts_path %>

app/views/storefronts/show.html.erb
<%= render 'header' %>

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-offset-3">
      	<h2 class="title is-2">
      		Store
      		
      		<% if can? :create, Product, :user_id => current_user.id %>
	        		<%= link_to 'New Product', new_product_path, class: 'button is-primary is-pulled-right' %>
	        	<% end %>  
      	</h2>
      	<hr>
      	<div class="columns">
      		<%= render @storefront.products %>
      	</div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-offset-3">
        <h2 class="title is-2">Info</h2>
        <hr>
        <p><%= @storefront.info %></p>
      </div>
    </div>
  </div>
</section>