config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :storefronts
  resources :products
  devise_for :users, controllers: { registrations: "registrations" }

  root 'welcome#index'
  post 'add_to_cart' => 'cart#add_to_cart'
  get 'view_cart' => 'cart#view_cart'
  

end

app/views/layouts/_navbar.html.erb
<nav class="nav">
  <div class="container">
    <div class="nav-left">
      <%= link_to(root_path,  class: 'nav-item is-branding') do %>
        <span class="icon">
          <i class="fa fa-home"></i>
        </span>
        <h1>farmshare</h1>
      <% end %>
      
    </div>

    <div class="nav-center">
    </div>

    <span class="nav-toggle">
      <span></span>
      <span></span>
      <span></span>
    </span>

    <div class="nav-right nav-menu">
      <%= link_to 'Cart', view_cart_path, class: 'nav-item' %>
      <% if user_signed_in? %>
        <div id="dropdown">
          <a class="nav-item is-active is-tab" id="dropdown-btn" ><%= current_user.email %>&nbsp;<i class="fa fa-caret-down" aria-hidden="true"></i></a>
          <div id="dropdown-content">
            <aside class="menu">
              <p class="menu-label">
                General
              </p>
              <ul class="menu-list">
                <li>
                  <% if current_user.seller? %>
                    <%= link_to 'Storefront', storefront_path(current_user.storefront) %>
                  <% else %>
                    <%= link_to 'Profile', profile_path(current_user.profile.id) %>
                  <% end %>
                </li>
                <li>
                  <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'is-active is-inverted' %>
                </li>
                <br>
              </ul>
            </aside>
          </div>
        </div>
      <% else %>
        <span class="nav-item">
          <%= link_to(new_user_registration_path,  class: 'button is-primary is-inverted') do %>
            <span class="icon">
              <i class="fa fa-chevron-circle-up" aria-hidden="true"></i>
            </span>
            <span>Sign up</span>
          <% end %>
          <%= link_to(new_user_session_path,  class: 'button is-primary') do %>
            <span class="icon">
              <i class="fa fa-sign-in"></i>
            </span>
            <span>Log in</span>
          <% end %>
        </span>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>farmshare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= yield %>

</body>
</html>